[package]
name = "imageview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.3.12"
regex = "1.6.0"
serde = "1.0.141"
serde_derive = "1.0.141"
serde_json = "1.0.82"
